name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Ini merupakan Pembelajaran Rust dari Kesalahan

  Untuk video jurnal dapat mengunjungi https://youtube.com/user/akbarpn136

  Perlu melakukan chat atau berminat gabung, masuk ke tautan berikut ini https://discord.gg/7dTG9sg

  ## Perubahan yang Dilakukan
  $CHANGES
categories:
  - title: '💣 Perubahan Total'
    label: 'breaking'
  - title: '🚀 Hal Baru'
    label: 'enhancement'
  - title: '🐛 Koreksi Bug'
    label: 'bug'
  - title: '🔨 Perawatan'
    label: 'maintenance'
  - title: '📝 Dokumentasi'
    label: 'documentation'
  - title: '🔗 Pembaruan Dependency'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'security'