[package]
name = "donatello"
version = "0.3.0"
authors = ["Arizal Akbar Zikri <akbarpn136@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
dotenv = "0.15.0"
env_logger = "0.7.1"
serde = "1.0.114"
serde_json = "1.0.56"
